package Interfaz;

public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public InterfazPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoPregunta = new javax.swing.ButtonGroup();
        RespuestacorrectaBTNGROUP = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BTNseleccionmultiple = new javax.swing.JRadioButton();
        TXTPREGUNTA = new javax.swing.JTextField();
        LB1 = new javax.swing.JLabel();
        BTNvf = new javax.swing.JRadioButton();
        TXTRESP2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTRESP3 = new javax.swing.JTextField();
        TXTRESP4 = new javax.swing.JTextField();
        TXTRESP1 = new javax.swing.JTextField();
        BTNGUAR = new javax.swing.JButton();
        BTNLIMP = new javax.swing.JButton();
        BTNELIM = new javax.swing.JButton();
        BTNMODI = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TXTID = new javax.swing.JTextField();
        RBTNRESP2 = new javax.swing.JRadioButton();
        RBTNRESP1 = new javax.swing.JRadioButton();
        RBTNRESP4 = new javax.swing.JRadioButton();
        RBTNRESP3 = new javax.swing.JRadioButton();
        TXTTIEMPO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BTNCREAREX = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CBNVL = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creacion de Preguntas");
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        BTNseleccionmultiple.setBackground(new java.awt.Color(245, 245, 245));
        tipoPregunta.add(BTNseleccionmultiple);
        BTNseleccionmultiple.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNseleccionmultiple.setText("Seleccion multiple");

        TXTPREGUNTA.setBackground(new java.awt.Color(245, 245, 245));
        TXTPREGUNTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTPREGUNTA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        TXTPREGUNTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTPREGUNTAKeyReleased(evt);
            }
        });

        LB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LB1.setText("Ingrese la Pregunta");

        BTNvf.setBackground(new java.awt.Color(245, 245, 245));
        tipoPregunta.add(BTNvf);
        BTNvf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNvf.setSelected(true);
        BTNvf.setText("Verdadero o Falso");

        TXTRESP2.setBackground(new java.awt.Color(245, 245, 245));
        TXTRESP2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTRESP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        TXTRESP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRESP2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de Pregunta");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Respuestas");

        TXTRESP3.setBackground(new java.awt.Color(245, 245, 245));
        TXTRESP3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTRESP3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        TXTRESP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRESP3ActionPerformed(evt);
            }
        });

        TXTRESP4.setBackground(new java.awt.Color(245, 245, 245));
        TXTRESP4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTRESP4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        TXTRESP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRESP4ActionPerformed(evt);
            }
        });

        TXTRESP1.setBackground(new java.awt.Color(245, 245, 245));
        TXTRESP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTRESP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        TXTRESP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRESP1ActionPerformed(evt);
            }
        });

        BTNGUAR.setBackground(new java.awt.Color(76, 175, 80));
        BTNGUAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNGUAR.setText("Guardar");
        BTNGUAR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        BTNLIMP.setBackground(new java.awt.Color(189, 189, 189));
        BTNLIMP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNLIMP.setText("Limpiar");
        BTNLIMP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        BTNELIM.setBackground(new java.awt.Color(244, 67, 54));
        BTNELIM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNELIM.setText("Eliminar");
        BTNELIM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTNELIM.setEnabled(false);

        BTNMODI.setBackground(new java.awt.Color(33, 150, 243));
        BTNMODI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNMODI.setText("Modificar");
        BTNMODI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTNMODI.setEnabled(false);
        BTNMODI.setPreferredSize(new java.awt.Dimension(67, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID");

        TXTID.setBackground(new java.awt.Color(245, 245, 245));
        TXTID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        RBTNRESP2.setBackground(new java.awt.Color(245, 245, 245));
        RespuestacorrectaBTNGROUP.add(RBTNRESP2);
        RBTNRESP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RBTNRESP2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBTNRESP2.setMaximumSize(new java.awt.Dimension(32, 32));
        RBTNRESP2.setMinimumSize(new java.awt.Dimension(32, 32));
        RBTNRESP2.setPreferredSize(new java.awt.Dimension(32, 32));

        RBTNRESP1.setBackground(new java.awt.Color(245, 245, 245));
        RespuestacorrectaBTNGROUP.add(RBTNRESP1);
        RBTNRESP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RBTNRESP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RBTNRESP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBTNRESP1.setMaximumSize(new java.awt.Dimension(32, 32));
        RBTNRESP1.setMinimumSize(new java.awt.Dimension(32, 32));
        RBTNRESP1.setPreferredSize(new java.awt.Dimension(32, 32));
        RBTNRESP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTNRESP1ActionPerformed(evt);
            }
        });

        RBTNRESP4.setBackground(new java.awt.Color(245, 245, 245));
        RespuestacorrectaBTNGROUP.add(RBTNRESP4);
        RBTNRESP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RBTNRESP4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBTNRESP4.setMaximumSize(new java.awt.Dimension(32, 32));
        RBTNRESP4.setMinimumSize(new java.awt.Dimension(32, 32));
        RBTNRESP4.setPreferredSize(new java.awt.Dimension(32, 32));

        RBTNRESP3.setBackground(new java.awt.Color(245, 245, 245));
        RespuestacorrectaBTNGROUP.add(RBTNRESP3);
        RBTNRESP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RBTNRESP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBTNRESP3.setMaximumSize(new java.awt.Dimension(32, 32));
        RBTNRESP3.setMinimumSize(new java.awt.Dimension(32, 32));
        RBTNRESP3.setPreferredSize(new java.awt.Dimension(32, 32));

        TXTTIEMPO.setBackground(new java.awt.Color(245, 245, 245));
        TXTTIEMPO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTTIEMPO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        TXTTIEMPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTIEMPOActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tiempo");

        BTNCREAREX.setBackground(new java.awt.Color(255, 152, 0));
        BTNCREAREX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNCREAREX.setText("Crear Examen");
        BTNCREAREX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Segundos");

        CBNVL.setBackground(new java.awt.Color(245, 245, 245));
        CBNVL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBNVL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Recordar", "Entender", "Aplicar", "Analizar", "Evaluar", "Crear" }));
        CBNVL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("NivelBloom");

        TABLA.setBackground(new java.awt.Color(224, 224, 224));
        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        TABLA.setSelectionBackground(new java.awt.Color(187, 222, 251));
        jScrollPane2.setViewportView(TABLA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNGUAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNMODI, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNLIMP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNELIM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BTNCREAREX, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TXTPREGUNTA, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(TXTID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(LB1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(BTNseleccionmultiple)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTNvf))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTRESP2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTRESP1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBTNRESP2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RBTNRESP1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTRESP3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTRESP4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBTNRESP3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RBTNRESP4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TXTTIEMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(CBNVL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(113, 113, 113)))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addComponent(LB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTPREGUNTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNseleccionmultiple)
                    .addComponent(BTNvf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RBTNRESP1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTRESP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTRESP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBTNRESP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(TXTRESP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RBTNRESP3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTRESP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBTNRESP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBNVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTTIEMPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BTNGUAR, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(BTNLIMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNMODI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNELIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(BTNCREAREX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTRESP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRESP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRESP2ActionPerformed

    private void TXTRESP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRESP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRESP3ActionPerformed

    private void TXTRESP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRESP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRESP4ActionPerformed

    private void TXTRESP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRESP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRESP1ActionPerformed

    private void TXTPREGUNTAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPREGUNTAKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPREGUNTAKeyReleased

    private void TXTTIEMPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTIEMPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTIEMPOActionPerformed

    private void RBTNRESP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTNRESP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBTNRESP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNCREAREX;
    public javax.swing.JButton BTNELIM;
    public javax.swing.JButton BTNGUAR;
    public javax.swing.JButton BTNLIMP;
    public javax.swing.JButton BTNMODI;
    public javax.swing.JRadioButton BTNseleccionmultiple;
    public javax.swing.JRadioButton BTNvf;
    public javax.swing.JComboBox<String> CBNVL;
    private javax.swing.JLabel LB1;
    public javax.swing.JRadioButton RBTNRESP1;
    public javax.swing.JRadioButton RBTNRESP2;
    public javax.swing.JRadioButton RBTNRESP3;
    public javax.swing.JRadioButton RBTNRESP4;
    private javax.swing.ButtonGroup RespuestacorrectaBTNGROUP;
    public javax.swing.JTable TABLA;
    public javax.swing.JTextField TXTID;
    public javax.swing.JTextField TXTPREGUNTA;
    public javax.swing.JTextField TXTRESP1;
    public javax.swing.JTextField TXTRESP2;
    public javax.swing.JTextField TXTRESP3;
    public javax.swing.JTextField TXTRESP4;
    public javax.swing.JTextField TXTTIEMPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup tipoPregunta;
    // End of variables declaration//GEN-END:variables
}
