package Interfaz;

import Modelo.ListarCreacion;

public class InterfazCreacion extends javax.swing.JFrame {


    public InterfazCreacion() {
        initComponents();
        
        ListarCreacion lc = new ListarCreacion();
        lc.MostrarTabla(TABLAPREGUNTAS);
        
        BTNINICIAR.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Obtener los IDs de la tabla TABLAPREGSELECT
            int filas = TABLAPREGSELECT.getRowCount();
            java.util.List<Integer> idsSeleccionados = new java.util.ArrayList<>();

            for (int i = 0; i < filas; i++) {
                Object valor = TABLAPREGSELECT.getValueAt(i, 0); // Se asume que la columna 0 es el ID
                if (valor != null) {
                    try {
                        int id = Integer.parseInt(valor.toString());
                        idsSeleccionados.add(id);
                    } catch (NumberFormatException e) {
                        System.err.println("ID inválido: " + valor);
                    }
                }
            }

            if (idsSeleccionados.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null, "No hay preguntas seleccionadas para el examen.");
            } else {
                // Iniciar el examen con los IDs
                new InterfazExamen(idsSeleccionados).setVisible(true);
                dispose(); // Cierra la ventana actual si quieres
                }
            }
        });
        
    }
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLAPREGSELECT = new javax.swing.JTable();
        TXTTIEMPOTOTAL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BTNINICIAR = new javax.swing.JButton();
        BTNSELECT = new javax.swing.JButton();
        BTNELIMPREG = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLAPREGUNTAS = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creacion de Examen");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        TABLAPREGSELECT.setBackground(new java.awt.Color(0, 204, 204));
        TABLAPREGSELECT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABLAPREGSELECT.setSelectionBackground(new java.awt.Color(153, 255, 255));
        TABLAPREGSELECT.setShowGrid(true);
        jScrollPane1.setViewportView(TABLAPREGSELECT);

        TXTTIEMPOTOTAL.setEditable(false);
        TXTTIEMPOTOTAL.setBackground(new java.awt.Color(204, 204, 204));
        TXTTIEMPOTOTAL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTTIEMPOTOTAL.setBorder(null);
        TXTTIEMPOTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTIEMPOTOTALActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("SEGUNDOS");

        BTNINICIAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNINICIAR.setText("Iniciar Examen");
        BTNINICIAR.setBorder(new javax.swing.border.MatteBorder(null));

        BTNSELECT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNSELECT.setText("Seleccionar Pregunta");
        BTNSELECT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BTNELIMPREG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNELIMPREG.setText("Eliminar Pregunta");
        BTNELIMPREG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNELIMPREG.setMaximumSize(new java.awt.Dimension(157, 27));
        BTNELIMPREG.setMinimumSize(new java.awt.Dimension(157, 27));
        BTNELIMPREG.setPreferredSize(new java.awt.Dimension(157, 27));

        TABLAPREGUNTAS.setBackground(new java.awt.Color(204, 102, 0));
        TABLAPREGUNTAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABLAPREGUNTAS.setSelectionBackground(new java.awt.Color(255, 153, 102));
        TABLAPREGUNTAS.setShowGrid(true);
        jScrollPane2.setViewportView(TABLAPREGUNTAS);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Tiempo Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TXTTIEMPOTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(BTNINICIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(BTNSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(BTNELIMPREG, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(576, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(566, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTTIEMPOTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSELECT)
                    .addComponent(BTNELIMPREG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BTNINICIAR, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTTIEMPOTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTIEMPOTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTIEMPOTOTALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCreacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCreacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCreacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCreacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCreacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNELIMPREG;
    public javax.swing.JButton BTNINICIAR;
    public javax.swing.JButton BTNSELECT;
    public javax.swing.JTable TABLAPREGSELECT;
    public javax.swing.JTable TABLAPREGUNTAS;
    public javax.swing.JTextField TXTTIEMPOTOTAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
